export const URL = {
  LOGIN: '/login',
  REGISTER: '/register',
  HOME: '/',
  WALLET: '/wallet',
  P2P: '/p2p',
  SWAP_TOKEN: '/swap-token',
  HOW_TO_BUY_CRYPTO: '/how-to-buy-crypto',
  HOW_TO_SELL: '/how-to-sell',
  HOW_TO_SWAP: '/how-to-swap',
  ABOUT_US: '/about-us',
  FAQs: '/privacy',
  NEWS: '/blog',
  HOW_REFERRAL_WORK: '/referral-disclosure',
  RELATION_DISCLOSURE: '/relation-disclosure',
  REFERRAL_REPORT: '/profile?tab=referral-reward',
};
